name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome, and thank your for reporting this issue! Our team is looking into it as we speak"
        pr-message: "Thanks for the Pull Request! Someone will respond when we have the time!"
